<?php

return [
    'production' => false,
    'baseUrl' => '',
    'title' => '2022 Annual Impact Report',
    'description' => 'We’re advancing affordable housing, child care, and impact-led lending—and making progress on our $5 billion commitment to racial equity.',
    'social'      => [
        'linkedin' => 'https://www.linkedin.com/company/low-income-investment-fund/',
        'facebook' => 'https://www.facebook.com/liifund/',
        'twitter'  => 'https://twitter.com/Liifund',
    ],
    'collections' => [
        'leaders' => [
            'items' => [
                [
                    'name'      => 'Daniel A. Nissenbaum',
                    'name_2'    => 'Reymundo Ocañas',
                    'title'     => 'LIIF Chief Executive Officer',
                    'title_2'   => 'LIIF Board Chair<br/>Director of Community Banking,<br/>Executive Vice President, PNC Bank',
                    'slug'      => 'dear-friends',
                    'excerpt'   => 'LIIF – like everyone else in our society – is learning to adjust to a “new normal.” For many the “new normal” began with the COVID-19 pandemic. For us, we began redefining LIIF’s “new normal” in 2019 with the crafting of our strategic plan. As we hit the halfway mark of this transformational four-year roadmap, we feel even more confident in our mission of advancing racial equity through equitable capital deployment, the creation and preservation of affordable housing, and ensuring more communities have access to quality child care and education.',
                    'image'     => '/assets/images/dan-and-rey.jpg',
                    'image_alt' => 'Daniel A. Nissenbaum and Reymundo Ocañas talking together while walking down the street.',
                    'image_pos' => 'top',
                    'link_url'  => 'https://www.liifund.org/justgoodcapital/2023/02/27/annual-letter-from-our-ceo-and-board-chair/',
                    'link_text' => 'Read the full letter',
                ],
                [
                    'name'      => 'Kimberly Latimer-Nelligan',
                    'title'     => 'President',
                    'slug'      => 'kim-president',
                    'excerpt'   => 'Our efforts continue to repair the long history of inequitable systems and financial institutions excluding Black, Latino, and other people and communities of color. I am pleased to share with you the progress we’ve made over the past year in redefining LIIF’s role in the community development ecosystem. In 2020, we set a goal to drive $5 billion in investments over the next decade to advance racial equity. Two years in, or 20% of the way, we are 26% there, having driven approximately $1.3 billion.',
                    'image'     => '/assets/images/Kim.png',
                    'image_alt' => 'Kimberly Latimer-Nelligan',
                    'link_url'  => 'https://www.liifund.org/justgoodcapital/2023/02/27/the-continued-advancement-of-our-impact-risk-profitability-irp-framework-and-toolkit/',
                    'image_pos' => 'bottom',
                    'link_text' => 'Read the full statement',
                ],
                [
                    'name'      => 'Lucy Arellano Baglieri',
                    'title'     => 'Executive Vice President and Chief Strategy Officer',
                    'slug'      => 'lucy-vp',
                    'excerpt'   => 'Halfway through this strategic plan, LIIF is reflecting not only on our work, but on the external environment. These past few years are marked by the height of the COVID-19 pandemic, extreme political turmoil and highly publicized murders of Black Americans by police. While these compounded inequities already faced by Black, Latino, and other people and communities of color, they also prompted a national reckoning on social injustice and racial inequity.',
                    'image'     => '/assets/images/Lucy.png',
                    'image_alt' => 'Lucy Arellano Baglieri',
                    'image_pos' => 'bottom',
                    'link_url'  => 'https://www.liifund.org/justgoodcapital/2023/02/27/redefining-equity-moving-beyond-what-to-how/',
                    'link_text' => 'Read the full statement',
                ],
            ],
        ],
        'cards' => [
            'items' => [
                [
                    'title'     => 'Community',
                    'slug'      => 'community',
                    'color'     => 'cyan-card',
                    'image'     => '/assets/images/card-bg-community.png',
                    'image_alt' => 'Young woman helping elderly man walk down the street',
                    'prefix'    => '$',
                    'stat'      => '3.2',
                    'unit'      => 'B',
                    'desc'      => 'invested in communities',
                ],
                [
                    'title'     => 'People',
                    'slug'      => 'people',
                    'color'     => 'blue-card',
                    'image'     => '/assets/images/card-bg-people.png',
                    'image_alt' => 'Woman with name tag smiling',
                    'prefix'    => '',
                    'stat'      => '2.5',
                    'unit'      => 'M',
                    'desc'      => 'people served',
                ],
                [
                    'title'     => 'Affordable Housing',
                    'slug'      => 'affordable-housing',
                    'color'     => 'yellow-card',
                    'image'     => '/assets/images/card-bg-affordable-housing.png',
                    'image_alt' => 'Man and woman smiling as the woman cuts vegetables',
                    'prefix'    => '',
                    'stat'      => '93',
                    'unit'      => 'K',
                    'desc'      => 'homes created or preserved',
                ],
                [
                    'title'     => 'Child Care',
                    'slug'      => 'child-care',
                    'color'     => 'green-card',
                    'image'     => '/assets/images/card-bg-child-care.png',
                    'image_alt' => 'Young boy placing a toy block on top of a toy block structure',
                    'prefix'    => '',
                    'stat'      => '302',
                    'unit'      => 'K',
                    'desc'      => 'child care slots created, preserved or enhanced',
                ],
            ],
        ],
        'articles' => [
            'items' => [
                [
                    'title'         => 'Impact-Led Lending',
                    'subtitle'      => 'LIIF’s New IRP Framework Redefines Risk, Centers Equity',
                    'slug'          => 'impact-led-lending',
                    'color'   => 'blue',
                    'image'         => '/assets/images/article-bg-impact-lending.png',
                    'image_alt'     => 'Mother sitting next to father as she holds her smiling baby.',
                    'image_pos'     => '',
                    'excerpt'       => 'LIIF’s strategic pillar of impact-led lending springs from our goal of nimble deployment of capital as the vehicle for effecting deeper impact in the communities we serve. With racial equity center to our mission, LIIF needed to consider where and how our efforts as a CDFI addressed the systemic inequities that create barriers to opportunity for historically excluded communities, particularly Black, Latino, and other people and communities of color. This meant moving beyond simply providing capital. We are redefining – <em>reimagining</em>, if you will – the impact these community investments will make for generations to come.',
                    'excerpt_pos'   => 'left',
                    'link_url'      => 'https://www.liifund.org/justgoodcapital/2023/02/27/impact-led-lending-liifs-new-irp-framework-redefines-risk-centers-equity/',
                    'link_text'     => 'Read more',
                    'spotlight'     => '<strong>THE “HOW”: The Villages of East River</strong><br/><em>Washington, D.C.</em><br/>Our Impact-Risk-Profitability (IRP) framework will guide us to deeper and more intentional impact. An example of a project with high impact priority elements is The Villages of East River. This 202-unit, scattered-site property comprising 16 buildings is located in the predominantly Black neighborhoods of Wards 7 and 8 of Southeast Washington, D.C. In our continuing efforts to create equity around housing, we provided a $6.4 million loan to NHT Communities, an SAHF member. The proceeds were used to refinance a maturing short-term acquisition loan, and LIIF assuming the first-lien position for the interim financing package that provided a bridge to a full recapitalization using tax-exempt bonds and 4% tax credits. Additionally, LIHTC was done through NAHT and our joint venture.',
                ],
                [
                    'title'         => 'Affordable Housing',
                    'subtitle'      => 'Solid Partnerships and a Foundation of LIIF\'s Work',
                    'slug'          => 'affordable-housing',
                    'color'   => 'blue',
                    'image'         => '/assets/images/article-bg-building.png',
                    'image_alt'     => 'Mother helping her son with homework.',
                    'image_pos'     => '',
                    'excerpt'       => 'LIIF has a longstanding history of innovative capital deployment that supports the expansion of the housing supply. While we have invested significant amounts to produce and preserve housing, we continued to grapple with a persistent housing crisis that significantly burdened Black, Latino, and other people and communities of color. As we embarked on our strategic planning journey, we recognized producing units was not enough. We needed a strategy that preserved affordable housing and addressed the systemic racism that encouraged the dismantling of Black and Latino communities. In order to make true impact we needed to create and leverage strategic partnerships.',
                    'excerpt_pos'   => 'right',
                    'link_url'      => 'https://www.liifund.org/justgoodcapital/2023/02/27/affordable-housing-solid-partnerships-and-a-foundation-of-liifs-work/',
                    'link_text'     => 'Read more',
                    'spotlight'     => '<strong>THE “HOW”: Frederick Samuel Apartments</strong><br/><em>New York City</em><br/>Showcasing LIIF’s continued commitment to the preservation of affordable housing is the renovation of Harlem\'s Frederick Samuel Apartments. This is an existing cluster of 664 affordable units to be preserved via the PACT program, New York City’s version of HUD’s Rental Assistance Demonstration (RAD) program. Genesis Companies and Lemor Development Group are using $1 million each from their LIIF Black Capital Developer Initiative (BDCI) financing to meet an anticipated 2025 completion date. This development exemplifies LIIF’s belief that healthy communities start with stable, quality affordable housing and early care and education: A co-located child care center will be rehabbed, as will small business spaces and a community center serving local families.',
                ],
                [
                    'title'         => 'Early Care and Education',
                    'subtitle'      => 'LIIF Supporting the Sector to Set Up Parents and Children for Success',
                    'subtitle_dt'   => 'LIIF Supporting the Sector to<br/>Set Up Parents and Children<br/>for Success',
                    'slug'          => 'children-success',
                    'color'   => 'blue',
                    'image'         => '/assets/images/article-bg-child-care.png',
                    'image_alt'     => 'Young toddler reaching right hand upwards.',
                    'image_pos'     => 'bottom',
                    'excerpt'       => 'Creating communities of opportunity, equity and well-being requires us to examine how historically excluded communities are able to access quality, affordable child care. Through our strategic planning process, LIIF identified early care and education (ECE) as a vital component to a thriving community because when children are provided with high-quality care and education, they are able to succeed. When providers are given adequate funding, they are able to create nurturing learning environments for the children in their communities. When parents are able to access reliable, quality care they can afford, they are able to provide for their families.',
                    'excerpt_pos'   => 'left',
                    'link_url'      => 'https://www.liifund.org/justgoodcapital/2023/02/27/early-care-and-education-liif-expanding-our-support-of-the-sector-to-set-up-parents-and-children-for-success/',
                    'link_text'     => 'Read more',
                    'spotlight'     => '<strong>THE “HOW”: Teddyland Family Day Care</strong><br/><em>Los Angeles</em><br/>LIIF awarded 317 grants via the City of Los Angeles COVID-19 Child Care Provider Grant Program, including to Owner Itza Sanchez of Teddyland Family Day Care in Torrance. The total awarded overall was $2.67 million, including $2.16 million of public resources and $510,000 of LIIF’s philanthropic resources received from the Wells Fargo Open of Business (OFB) program. Explains Itza, “Thanks to the grant I was able to remain open during the pandemic. I was able to keep my staff, plus pay rent/mortgage, taxes, insurance and utilities.”',
                ],
            ],
        ],
        'supporters' => [
            'items' => [
                [
                    'label' => 'Funders & Donors',
                    'slug' => 'funders-donors',
                    'items' => [
                        'Ballmer Group',
                        'Bank of America Charitable Foundation',
                        'Cathay Bank Foundation',
                        'Charles Schwab Bank, SSB',
                        'CIT/OneWest Bank, N.A. (First Citizens Bank)',
                        'City and County of San Francisco',
                        'CTBC Bank',
                        'D.C. Office of the State Superintendent of Education',
                        'Georgia Power Foundation',
                        'Goldman Sachs Foundation',
                        'Heising-Simons Foundation',
                        'HSBC Bank USA, N.A.',
                        'JPB Foundation',
                        'JPMorgan Chase Foundation',
                        'Kresge Foundation',
                        'Manufacturers Bank',
                        'Marisla Foundation',
                        'Morgan Stanley',
                        'New York Community Trust',
                        'Robert Wood Johnson Foundation',
                        'Santander Bank',
                        'Signature Bank',
                        'Truist Foundation',
                        'U.S. Bank National Association',
                        'U.S. Department of the Treasury CDFI Fund',
                        'Wells Fargo Foundation',
                    ],
                ],
                [
                    'label' => 'Investors',
                    'slug' => 'investors',
                    'items' => [
                        'Amalgamated Bank',
                        'Bank of America Community Development ',
                        'BBVA Compass Bank ',
                        'BDS 2012 Qualified Annuity Trust',
                        'Capital One',
                        'Charles Schwab Bank',
                        'CIT Bank',
                        'Community Foundation for Greater Atlanta',
                        'Deutsche Bank Trust Company Americas',
                        'Erich & Hannah Sachs Foundation',
                        'Federal Home Loan Bank of San Francisco',
                        'First Republic Bank',
                        'Ford Foundation',
                        'Goldman Sachs',
                        'HSBC Bank USA',
                        'JP Morgan Chase',
                        'Kalliopeia Foundation',
                        'Kresge Foundation',
                        'Mercy Investment Services, Inc.',
                        'Metropolitan Transportation Commission',
                        'Mizuho Bank (USA)',
                        'Morgan Stanley',
                        'MUFG Union Bank',
                        'Northern Trust',
                        'NY Quarterly Meeting of the Religious Society of Friends',
                        'San Francisco Friends School',
                        'Satterberg Foundation',
                        'Signature Bank',
                        'Sisters of Charity of the Incarnate Word',
                        'Trinity Health Corporation',
                        'Truist Bank',
                        'U.S. Bank National Association',
                        'Wells Fargo ',
                    ],
                ],
                [
                    'label' => 'Financing Partners',
                    'slug' => 'financing-partners',
                    'items' => [
                        '609 Broad Street ',
                        'Arnold Ventures',
                        'Bay Area Metropolitan Transportation Commission',
                        'California Department of Housing and Community Development ',
                        'Calvert Impact Capital/Momentus ',
                        'Capital Impact Partners',
                        'City First Bank ',
                        'Community Loan Fund of New Jersey',
                        'DC Department of Housing and Community Development',
                        'Enterprise Community Partners',
                        'Enterprise Community Loan Fund',
                        'Goldman Sachs Bank USA',
                        'Housing Partnership Network',
                        'Invest Atlanta',
                        'JPMorgan Chase & Co.',
                        'Lift to Rise',
                        'Los Angeles County Metropolitan Transportation Authority',
                        'LOCUS Impact Investing',
                        'Massachusetts Housing Investment Corporation',
                        'Mercy Loan Fund',
                        'National Affordable Housing Trust',
                        'National Resources Defense Council',
                        'New York City Acquisition Fund',
                        'New York City Housing Development Corporation',
                        'Nonprofit Finance Fund',
                        'Purpose Built Communities',
                        'Prudential Financial',
                        'Reinvestment Fund',
                        'Self-Help Federal Credit Union',
                        'UMC Benefit Board',
                    ],
                ],
                [
                    'label' => 'Board of Directors',
                    'slug' => 'board-of-directors',
                    'officers' => [
                        [
                            'name' => 'Reymundo Ocañas, Chair',
                            'title' => 'Director of Community Development Banking,<br/>PNC Bank',
                        ],
                        [
                            'name' => 'Carol Naughton, Treasurer',
                            'title' => 'CEO, Purpose Built Communities',
                        ],
                        [
                            'name' => 'Russell Bruemmer, Secretary',
                            'title' => 'Retired Partner, Wilmer Cutler Pickering<br/>Hale and Dorr',
                        ],
                    ],
                    'directors' => [    
                        [
                            'name' => 'Margaret Anadu',
                            'title' => 'Senior Partner, The Vistria Group',
                        ],
                        [
                            'name' => 'Derek R.B. Douglas*',
                            'title' => 'Vice President for Civic Engagement<br/>and External Affairs<br/>University of Chicago<br/>(*termed off in FY23)',
                        ],
                        [
                            'name' => 'David Fleming, M.D.',
                            'title' => 'Distinguished Fellow, Trust for<br/>America’s Health',
                        ],
                        [
                            'name' => 'Donna Gambrell',
                            'title' => 'President & CEO, Appalachian<br/>Community Capital',
                        ],
                        [
                            'name' => 'Calvin Gladney',
                            'title' => 'President & CEO, Smart Growth America',
                        ],
                        [
                            'name' => 'Dr. Myra Jones-Taylor',
                            'title' => 'Chief Policy Officer, Urban Institute<br/>(*departed)',
                        ],
                        [
                            'name' => 'William C. Kelly, Jr.',
                            'title' => 'Founder, Stewards of Affordable Housing<br/>for the Future',
                        ],
                        [
                            'name' => 'Dionne Nelson',
                            'title' => 'President & CEO, Laurel Street',
                        ],
                        [
                            'name' => 'Daniel A. Nissenbaum',
                            'title' => 'CEO, Low Income Investment Fund',
                        ],
                        [
                            'name' => 'Michael A. Solomon',
                            'title' => 'Managing Director of Community<br/>Development, Charles Schwab<br/>Bank & Trust Services',
                        ],
                        [
                            'name' => 'Roy Swan',
                            'title' => 'Head of Mission Investments,<br/>Ford Foundation<br/>(*departed)',
                        ],
                    ],
                    'new_members' => [
                        [
                            'name' => 'Tawanna A. Black',
                            'title' => 'Founder and CEO of Center for<br/>Economic Inclusion',
                        ],
                        [
                            'name' => 'Eileen Fitzgerald',
                            'title' => 'Former Head of Housing Affordability<br/>Philanthropy, Wells Fargo',
                        ],
                        [
                            'name' => 'Jessica Sager',
                            'title' => 'CEO, All our Kin, Inc.',
                        ],
                    ],
                ],
                [
                    'label' => 'Committees',
                    'slug' => 'committees',
                    'items' => [
                        [
                            'name' => 'Executive Committee',
                            'col_start' => '1',
                            'col_end' => '',
                            'items' => [
                                [
                                    'name' => 'Rey Ocañas',
                                    'title' => 'Chair',
                                ],
                                [
                                    'name' => 'Russ Bruemmer',
                                    'title' => 'Secretary',
                                ],
                                [
                                    'name' => 'Carol Naughton',
                                    'title' => 'Treasurer',
                                ],
                            ],
                        ],
                        [
                            'name' => 'Finance Committee',
                            'col_start' => '',
                            'col_end' => '1',
                            'items' => [
                                [
                                    'name' => 'Carol Naughton',
                                    'title' => 'Chair',
                                ],
                                [
                                    'name' => 'Margaret Anadu',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'David Fleming',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Dionne Nelson',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Margaret Salazar',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Daniel A. Nissenbaum',
                                    'title' => '(alternate)',
                                ],
                            ],
                        ],
                        [
                            'name' => 'Ad Hoc Governance',
                            'col_start' => '2',
                            'col_end' => '',
                            'items' => [
                                [
                                    'name' => 'Derek Douglas',
                                    'title' => 'Chair<br/>(*termed off in FY23)',
                                ],
                                [
                                    'name' => 'Russ Bruemmer',
                                    'title' => '',
                                ],
                            ],
                        ],
                        [
                            'name' => 'Lending Risk Committee',
                            'col_start' => '',
                            'col_end' => '2',
                            'items' => [
                                [
                                    'name' => 'Bill Kelly',
                                    'title' => 'Chair',
                                ],
                                [
                                    'name' => 'Russ Bruemmer',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Donna Gambrell',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Calvin Gladney',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Michael Solomon',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Daniel A. Nissenbaum',
                                    'title' => '(alternate)',
                                ],
                            ],
                        ],
                        [
                            'name' => 'Audit Committee',
                            'col_start' => '3',
                            'col_end' => '3',
                            'items' => [
                                [
                                    'name' => 'Russ Bruemmer',
                                    'title' => 'Chair',
                                ],
                                [
                                    'name' => 'Derek Douglas',
                                    'title' => '',
                                ],
                                [
                                    'name' => 'Bill Kelly',
                                    'title' => '',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'label' => 'Senior Staff',
                    'slug' => 'senior-staff',
                    'items' => [
                        [
                            'name' => 'Daniel A. Nissenbaum',
                            'title' => 'Chief Executive Officer',
                            'col_start' => '1',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Lucy Arellano Baglieri',
                            'title' => 'Chief Strategy Officer and Executive<br/>Vice President',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Kimberly Latimer-Nelligan',
                            'title' => 'President',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Panagiota Mahendru',
                            'title' => 'Chief Financial Officer and Executive<br/>Vice President',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Denise Noel',
                            'title' => 'General Counsel and Executive<br/>Vice President',
                            'col_start' => '',
                            'col_end' => '1',
                        ],
                        [
                            'name' => 'Rachel Bluestein',
                            'title' => 'Senior Vice President,<br/>Chief Programs Officer',
                            'col_start' => '2',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Susan Hyman',
                            'title' => 'Senior Vice President,<br/>Chief Credit Officer',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Stephanie McFadden',
                            'title' => 'Senior Vice President,<br/>Chief Lending Officer',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Walter Chen',
                            'title' => 'Vice President & Associate<br/>General Counsel',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Angie Garling',
                            'title' => 'Vice President, Early Care<br/>and Education',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'LaToya Kyle',
                            'title' => 'Vice President Southeast Region',
                            'col_start' => '',
                            'col_end' => '2',
                        ],
                        [
                            'name' => 'Maygen Moore',
                            'title' => 'Vice President Affordable Housing<br/>and National Lending Initiatives',
                            'col_start' => '3',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Kirsten Shaw',
                            'title' => 'Vice President, Northeast and<br/>Mid‐Atlantic Regions',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Carolyn Smith',
                            'title' => 'Vice President, Strategic<br/>Communications and Influence',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Jessica Standiford',
                            'title' => 'Vice President, Development and<br/>Impact Investing',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Pam Berkowitz',
                            'title' => 'Market Director &mdash; Western Region',
                            'col_start' => '',
                            'col_end' => '',
                        ],
                        [
                            'name' => 'Eliisa Frazier',
                            'title' => 'Director of Racial Equity and<br/>Impact Lending',
                            'col_start' => '',
                            'col_end' => '3',
                        ],
                    ],
                ],
            ],
        ],
        'financials' => [
            'items' => [
                [
                    'label' => 'Financial Position',
                    'slug' => 'financial-position',
                    'items' => [],
                ],
                [
                    'label' => 'Financial Activities',
                    'slug' => 'financial-activities',
                    'items' => [],
                ],
            ],
        ],
    ],
];
